// <auto-generated />
using System;
using Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260507052320_AddingImagePrefix")]
    partial class AddingImagePrefix
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Deliveries.DeliveryTracking", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("AcceptedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("accepted_at");

                    b.Property<DateTime?>("DeliveredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("delivered_at");

                    b.Property<Guid>("DeliveryManId")
                        .HasColumnType("uuid")
                        .HasColumnName("delivery_man_id");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_id");

                    b.Property<DateTime?>("PickedUpAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("picked_up_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_delivery_trackings");

                    b.HasIndex("OrderId")
                        .HasDatabaseName("ix_delivery_trackings_order_id");

                    b.HasIndex("DeliveryManId", "Status")
                        .HasDatabaseName("ix_delivery_trackings_driver_status");

                    b.ToTable("delivery_trackings", (string)null);
                });

            modelBuilder.Entity("Domain.Meals.Meal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ChefId")
                        .HasColumnType("uuid")
                        .HasColumnName("chef_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CuisineType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("cuisine_type");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<string>("DishType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("dish_type");

                    b.Property<string>("ImageKeyPrefix")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("image_key_prefix");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("image_url");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("boolean")
                        .HasColumnName("is_available");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_meals");

                    b.HasIndex("CuisineType")
                        .HasDatabaseName("ix_meals_cuisine_type")
                        .HasFilter("cuisine_type IS NOT NULL");

                    b.HasIndex("DishType")
                        .HasDatabaseName("ix_meals_dish_type");

                    b.ToTable("meals", (string)null);
                });

            modelBuilder.Entity("Domain.Orders.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CancellationReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("cancellation_reason");

                    b.Property<Guid>("ChefId")
                        .HasColumnType("uuid")
                        .HasColumnName("chef_id");

                    b.Property<DateTime?>("ConfirmedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("confirmed_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<DateTime?>("DeliveredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("delivered_at");

                    b.Property<Guid?>("DeliveryManId")
                        .HasColumnType("uuid")
                        .HasColumnName("delivery_man_id");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("payment_method");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("payment_status");

                    b.Property<DateTime?>("ReadyAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ready_at");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("rejection_reason");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_orders");

                    b.HasIndex("ChefId", "Status")
                        .HasDatabaseName("ix_orders_chef_status");

                    b.HasIndex("CustomerId", "CreatedAt")
                        .HasDatabaseName("ix_orders_customer_created");

                    b.ToTable("orders", (string)null);
                });

            modelBuilder.Entity("Domain.Users.ChefProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("AppliedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("applied_at");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("text")
                        .HasColumnName("avatar_url");

                    b.Property<string>("HealthCertificateReference")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("health_certificate_reference");

                    b.Property<string>("PersonalIdReference")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("personal_id_reference");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("rejection_reason");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reviewed_at");

                    b.Property<Guid?>("ReviewedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("reviewed_by_user_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_chef_profiles");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_chef_profiles_user_id");

                    b.ToTable("chef_profiles", (string)null);
                });

            modelBuilder.Entity("Domain.Users.DeliveryManProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("AppliedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("applied_at");

                    b.Property<string>("PersonalIdNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("personal_id_number");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("rejection_reason");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reviewed_at");

                    b.Property<Guid?>("ReviewedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("reviewed_by_user_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("VehicleType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("vehicle_type");

                    b.HasKey("Id")
                        .HasName("pk_delivery_man_profiles");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_delivery_man_profiles_user_id");

                    b.ToTable("delivery_man_profiles", (string)null);
                });

            modelBuilder.Entity("Domain.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("last_name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Infrastructure.Persistence.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Error")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("error");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_outbox_messages");

                    b.HasIndex("ProcessedAt")
                        .HasDatabaseName("ix_outbox_messages_processed_at")
                        .HasFilter("processed_at IS NULL");

                    b.ToTable("outbox_messages", (string)null);
                });

            modelBuilder.Entity("Domain.Deliveries.DeliveryTracking", b =>
                {
                    b.OwnsOne("Domain.Common.Location", "DropoffLocation", b1 =>
                        {
                            b1.Property<Guid>("DeliveryTrackingId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("AddressLine")
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("dropoff_location_address");

                            b1.Property<double>("Latitude")
                                .HasColumnType("double precision")
                                .HasColumnName("dropoff_location_lat");

                            b1.Property<double>("Longitude")
                                .HasColumnType("double precision")
                                .HasColumnName("dropoff_location_lng");

                            b1.Property<Point>("_point")
                                .IsRequired()
                                .HasColumnType("geography(Point,4326)")
                                .HasColumnName("dropoff_location");

                            b1.HasKey("DeliveryTrackingId");

                            b1.ToTable("delivery_trackings");

                            b1.WithOwner()
                                .HasForeignKey("DeliveryTrackingId")
                                .HasConstraintName("fk_delivery_trackings_delivery_trackings_id");
                        });

                    b.OwnsOne("Domain.Common.Location", "PickupLocation", b1 =>
                        {
                            b1.Property<Guid>("DeliveryTrackingId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("AddressLine")
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("pickup_location_address");

                            b1.Property<double>("Latitude")
                                .HasColumnType("double precision")
                                .HasColumnName("pickup_location_lat");

                            b1.Property<double>("Longitude")
                                .HasColumnType("double precision")
                                .HasColumnName("pickup_location_lng");

                            b1.Property<Point>("_point")
                                .IsRequired()
                                .HasColumnType("geography(Point,4326)")
                                .HasColumnName("pickup_location");

                            b1.HasKey("DeliveryTrackingId");

                            b1.ToTable("delivery_trackings");

                            b1.WithOwner()
                                .HasForeignKey("DeliveryTrackingId")
                                .HasConstraintName("fk_delivery_trackings_delivery_trackings_id");
                        });

                    b.Navigation("DropoffLocation")
                        .IsRequired();

                    b.Navigation("PickupLocation")
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Meals.Meal", b =>
                {
                    b.OwnsMany("Domain.Meals.MealVariant", "Variants", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<bool>("IsDefault")
                                .HasColumnType("boolean")
                                .HasColumnName("is_default");

                            b1.Property<Guid>("MealId")
                                .HasColumnType("uuid")
                                .HasColumnName("meal_id");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("name");

                            b1.HasKey("Id")
                                .HasName("pk_meal_variants");

                            b1.HasIndex("MealId", "IsDefault")
                                .HasDatabaseName("ix_meal_variants_default")
                                .HasFilter("is_default = true");

                            b1.ToTable("meal_variants", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("MealId")
                                .HasConstraintName("fk_meal_variants_meals_meal_id");

                            b1.OwnsOne("Domain.Common.Money", "Price", b2 =>
                                {
                                    b2.Property<Guid>("MealVariantId")
                                        .HasColumnType("uuid")
                                        .HasColumnName("id");

                                    b2.Property<decimal>("Amount")
                                        .HasColumnType("numeric(18,2)")
                                        .HasColumnName("price_amount");

                                    b2.Property<string>("Currency")
                                        .IsRequired()
                                        .HasMaxLength(3)
                                        .HasColumnType("character varying(3)")
                                        .HasColumnName("price_currency");

                                    b2.HasKey("MealVariantId");

                                    b2.ToTable("meal_variants");

                                    b2.WithOwner()
                                        .HasForeignKey("MealVariantId")
                                        .HasConstraintName("fk_meal_variants_meal_variants_id");
                                });

                            b1.Navigation("Price")
                                .IsRequired();
                        });

                    b.OwnsMany("Domain.Meals.SideDish", "SideDishes", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("Description")
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("description");

                            b1.Property<bool>("IsRequired")
                                .HasColumnType("boolean")
                                .HasColumnName("is_required");

                            b1.Property<Guid>("MealId")
                                .HasColumnType("uuid")
                                .HasColumnName("meal_id");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("name");

                            b1.HasKey("Id")
                                .HasName("pk_side_dishes");

                            b1.HasIndex("MealId")
                                .HasDatabaseName("ix_side_dishes_meal_id");

                            b1.ToTable("side_dishes", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("MealId")
                                .HasConstraintName("fk_side_dishes_meals_meal_id");

                            b1.OwnsOne("Domain.Common.Money", "Price", b2 =>
                                {
                                    b2.Property<Guid>("SideDishId")
                                        .HasColumnType("uuid")
                                        .HasColumnName("id");

                                    b2.Property<decimal>("Amount")
                                        .HasColumnType("numeric(18,2)")
                                        .HasColumnName("price_amount");

                                    b2.Property<string>("Currency")
                                        .IsRequired()
                                        .HasMaxLength(3)
                                        .HasColumnType("character varying(3)")
                                        .HasColumnName("price_currency");

                                    b2.HasKey("SideDishId");

                                    b2.ToTable("side_dishes");

                                    b2.WithOwner()
                                        .HasForeignKey("SideDishId")
                                        .HasConstraintName("fk_side_dishes_side_dishes_id");
                                });

                            b1.Navigation("Price")
                                .IsRequired();
                        });

                    b.OwnsMany("Domain.Meals.ToppingGroup", "ToppingGroups", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<int>("MaxSelections")
                                .HasColumnType("integer")
                                .HasColumnName("max_selections");

                            b1.Property<Guid>("MealId")
                                .HasColumnType("uuid")
                                .HasColumnName("meal_id");

                            b1.Property<int>("MinSelections")
                                .HasColumnType("integer")
                                .HasColumnName("min_selections");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("name");

                            b1.HasKey("Id")
                                .HasName("pk_topping_groups");

                            b1.HasIndex("MealId")
                                .HasDatabaseName("ix_topping_groups_meal_id");

                            b1.ToTable("topping_groups", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("MealId")
                                .HasConstraintName("fk_topping_groups_meals_meal_id");

                            b1.OwnsMany("Domain.Meals.ToppingOption", "Options", b2 =>
                                {
                                    b2.Property<Guid>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("uuid")
                                        .HasColumnName("id");

                                    b2.Property<string>("Name")
                                        .IsRequired()
                                        .HasMaxLength(100)
                                        .HasColumnType("character varying(100)")
                                        .HasColumnName("name");

                                    b2.Property<Guid>("ToppingGroupId")
                                        .HasColumnType("uuid")
                                        .HasColumnName("topping_group_id");

                                    b2.HasKey("Id")
                                        .HasName("pk_topping_options");

                                    b2.HasIndex("ToppingGroupId")
                                        .HasDatabaseName("ix_topping_options_topping_group_id");

                                    b2.ToTable("topping_options", (string)null);

                                    b2.WithOwner()
                                        .HasForeignKey("ToppingGroupId")
                                        .HasConstraintName("fk_topping_options_topping_groups_topping_group_id");

                                    b2.OwnsOne("Domain.Common.Money", "ExtraPrice", b3 =>
                                        {
                                            b3.Property<Guid>("ToppingOptionId")
                                                .HasColumnType("uuid")
                                                .HasColumnName("id");

                                            b3.Property<decimal>("Amount")
                                                .HasColumnType("numeric(18,2)")
                                                .HasColumnName("extra_price_amount");

                                            b3.Property<string>("Currency")
                                                .IsRequired()
                                                .HasMaxLength(3)
                                                .HasColumnType("character varying(3)")
                                                .HasColumnName("extra_price_currency");

                                            b3.HasKey("ToppingOptionId");

                                            b3.ToTable("topping_options");

                                            b3.WithOwner()
                                                .HasForeignKey("ToppingOptionId")
                                                .HasConstraintName("fk_topping_options_topping_options_id");
                                        });

                                    b2.Navigation("ExtraPrice")
                                        .IsRequired();
                                });

                            b1.Navigation("Options");
                        });

                    b.Navigation("SideDishes");

                    b.Navigation("ToppingGroups");

                    b.Navigation("Variants");
                });

            modelBuilder.Entity("Domain.Orders.Order", b =>
                {
                    b.OwnsOne("Domain.Common.Location", "DeliveryLocation", b1 =>
                        {
                            b1.Property<Guid>("OrderId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("AddressLine")
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("delivery_location_address");

                            b1.Property<double>("Latitude")
                                .HasColumnType("double precision")
                                .HasColumnName("delivery_location_lat");

                            b1.Property<double>("Longitude")
                                .HasColumnType("double precision")
                                .HasColumnName("delivery_location_lng");

                            b1.Property<Point>("_point")
                                .IsRequired()
                                .HasColumnType("geography(Point,4326)")
                                .HasColumnName("delivery_location");

                            b1.HasKey("OrderId");

                            b1.HasIndex("_point")
                                .HasDatabaseName("ix_orders_delivery_location_gist");

                            NpgsqlIndexBuilderExtensions.HasMethod(b1.HasIndex("_point"), "gist");

                            b1.ToTable("orders");

                            b1.WithOwner()
                                .HasForeignKey("OrderId")
                                .HasConstraintName("fk_orders_orders_id");
                        });

                    b.OwnsMany("Domain.Orders.OrderItem", "Items", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<Guid>("MealId")
                                .HasColumnType("uuid")
                                .HasColumnName("meal_id");

                            b1.Property<string>("MealName")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("meal_name");

                            b1.Property<Guid>("MealVariantId")
                                .HasColumnType("uuid")
                                .HasColumnName("meal_variant_id");

                            b1.Property<Guid>("OrderId")
                                .HasColumnType("uuid")
                                .HasColumnName("order_id");

                            b1.Property<int>("Quantity")
                                .HasColumnType("integer")
                                .HasColumnName("quantity");

                            b1.Property<string>("VariantName")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("variant_name");

                            b1.Property<string>("_sideDishesJson")
                                .IsRequired()
                                .HasColumnType("jsonb")
                                .HasColumnName("selected_side_dishes");

                            b1.Property<string>("_toppingsJson")
                                .IsRequired()
                                .HasColumnType("jsonb")
                                .HasColumnName("selected_toppings");

                            b1.HasKey("Id")
                                .HasName("pk_order_items");

                            b1.HasIndex("OrderId")
                                .HasDatabaseName("ix_order_items_order_id");

                            b1.ToTable("order_items", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("OrderId")
                                .HasConstraintName("fk_order_items_orders_order_id");

                            b1.OwnsOne("Domain.Common.Money", "VariantPrice", b2 =>
                                {
                                    b2.Property<Guid>("OrderItemId")
                                        .HasColumnType("uuid")
                                        .HasColumnName("id");

                                    b2.Property<decimal>("Amount")
                                        .HasColumnType("numeric(18,2)")
                                        .HasColumnName("variant_price_amount");

                                    b2.Property<string>("Currency")
                                        .IsRequired()
                                        .HasMaxLength(3)
                                        .HasColumnType("character varying(3)")
                                        .HasColumnName("variant_price_currency");

                                    b2.HasKey("OrderItemId");

                                    b2.ToTable("order_items");

                                    b2.WithOwner()
                                        .HasForeignKey("OrderItemId")
                                        .HasConstraintName("fk_order_items_order_items_id");
                                });

                            b1.Navigation("VariantPrice")
                                .IsRequired();
                        });

                    b.Navigation("DeliveryLocation")
                        .IsRequired();

                    b.Navigation("Items");
                });

            modelBuilder.Entity("Domain.Users.ChefProfile", b =>
                {
                    b.HasOne("Domain.Users.User", null)
                        .WithOne("ChefProfile")
                        .HasForeignKey("Domain.Users.ChefProfile", "UserId")
                        .HasConstraintName("fk_chef_profiles_users_user_id");

                    b.OwnsOne("Domain.Common.Location", "OperationLocation", b1 =>
                        {
                            b1.Property<Guid>("ChefProfileId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("AddressLine")
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("operation_location_address");

                            b1.Property<double>("Latitude")
                                .HasColumnType("double precision")
                                .HasColumnName("operation_location_lat");

                            b1.Property<double>("Longitude")
                                .HasColumnType("double precision")
                                .HasColumnName("operation_location_lng");

                            b1.Property<Point>("_point")
                                .IsRequired()
                                .HasColumnType("geography(Point,4326)")
                                .HasColumnName("operation_location");

                            b1.HasKey("ChefProfileId");

                            b1.HasIndex("_point")
                                .HasDatabaseName("ix_chef_profiles_location_gist");

                            NpgsqlIndexBuilderExtensions.HasMethod(b1.HasIndex("_point"), "gist");

                            b1.ToTable("chef_profiles");

                            b1.WithOwner()
                                .HasForeignKey("ChefProfileId")
                                .HasConstraintName("fk_chef_profiles_chef_profiles_id");
                        });

                    b.Navigation("OperationLocation")
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Users.DeliveryManProfile", b =>
                {
                    b.HasOne("Domain.Users.User", null)
                        .WithOne("DeliveryManProfile")
                        .HasForeignKey("Domain.Users.DeliveryManProfile", "UserId")
                        .HasConstraintName("fk_delivery_man_profiles_users_user_id");

                    b.OwnsOne("Domain.Common.Location", "CurrentLocation", b1 =>
                        {
                            b1.Property<Guid>("DeliveryManProfileId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("AddressLine")
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("current_location_address");

                            b1.Property<double>("Latitude")
                                .HasColumnType("double precision")
                                .HasColumnName("current_location_lat");

                            b1.Property<double>("Longitude")
                                .HasColumnType("double precision")
                                .HasColumnName("current_location_lng");

                            b1.Property<Point>("_point")
                                .HasColumnType("geography(Point,4326)")
                                .HasColumnName("current_location");

                            b1.HasKey("DeliveryManProfileId");

                            b1.ToTable("delivery_man_profiles");

                            b1.WithOwner()
                                .HasForeignKey("DeliveryManProfileId")
                                .HasConstraintName("fk_delivery_man_profiles_delivery_man_profiles_id");
                        });

                    b.Navigation("CurrentLocation");
                });

            modelBuilder.Entity("Domain.Users.User", b =>
                {
                    b.OwnsOne("Domain.Common.Location", "DefaultDeliveryLocation", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("AddressLine")
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("default_location_address");

                            b1.Property<double>("Latitude")
                                .HasColumnType("double precision")
                                .HasColumnName("default_location_lat");

                            b1.Property<double>("Longitude")
                                .HasColumnType("double precision")
                                .HasColumnName("default_location_lng");

                            b1.Property<Point>("_point")
                                .HasColumnType("geography(Point,4326)")
                                .HasColumnName("default_location");

                            b1.HasKey("UserId");

                            b1.ToTable("users");

                            b1.WithOwner()
                                .HasForeignKey("UserId")
                                .HasConstraintName("fk_users_users_id");
                        });

                    b.Navigation("DefaultDeliveryLocation");
                });

            modelBuilder.Entity("Domain.Users.User", b =>
                {
                    b.Navigation("ChefProfile");

                    b.Navigation("DeliveryManProfile");
                });
#pragma warning restore 612, 618
        }
    }
}
